library(llamar)
# FFP data for Kyla: DHS since 2000

countries = c('BD','BF','BU','KH','TD','CD','ET','GH','GN','HT','HN','IA','ID','KE','LB','MD','MW','ML','MR','MZ','NP','NI','RW','SL','UG','ZM','ZW')
# 'SD','GU', #(no recent data)
years = paste0(seq(2000,2016), collapse = ',')
apiKey = 'USAAID-405632'
indicators = 'CM_ECMT_C_PNR,CH_DIAR_C_DIA,CH_DIAR_C_DIA,CH_DSTL_C_SAF,CH_DSTL_C_SAF,CN_NUTS_C_HA2,CN_NUTS_C_HAM,CN_NUTS_C_WH2,CN_NUTS_C_WA2,CN_BFDR_C_MDE,WS_SRCE_H_IMP,WS_SRCE_H_PIP,WS_SRCE_H_PYD,WS_SRCE_H_TAP,WS_SRCE_H_PNB,WS_SRCE_H_POY,WS_SRCE_H_TUB,WS_SRCE_H_PWU,WS_SRCE_H_PWL,WS_SRCE_H_PSU,WS_SRCE_H_PSG,WS_SRCE_H_RNW,WS_SRCE_H_BOT,WS_SRCE_H_FLT,WS_SRCE_H_NIM,WS_SRCE_H_UWU,WS_SRCE_H_UWL,WS_SRCE_H_USG,WS_SRCE_H_USG,WS_SRCE_H_TNK,WS_SRCE_H_CRT,WS_SRCE_H_VND,WS_SRCE_H_SCH,WS_SRCE_H_SRF,WS_SRCE_H_OTH,WS_TIME_H_ONP,WS_TIME_H_L30,WS_TIME_H_30P,WS_WTRT_H_BOL,WS_WTRT_H_BLC,WS_WTRT_H_STN,WS_WTRT_H_CER,WS_WTRT_H_SOL,WS_WTRT_H_OTH,WS_WTRT_H_NTR,WS_WTRT_H_APP,WS_TLET_H_IMP,WS_TLET_H_FSW,WS_TLET_H_FSP,WS_TLET_H_FPT,WS_TLET_H_VIP,WS_TLET_H_PSL,WS_TLET_H_COM,WS_TLET_H_IMO,WS_TLET_H_SHR,WS_TLET_H_SSW,WS_TLET_H_SSP,WS_TLET_H_SPT,WS_TLET_H_SVP,WS_TLET_H_SSL,WS_TLET_H_SCM,WS_TLET_H_SHO,WS_TLET_H_NIM,WS_TLET_H_NFL,WS_TLET_H_NPT,WS_TLET_H_NBK,WS_TLET_H_NHG,WS_TLET_H_NWT,WS_TLET_H_NFC,WS_TLET_H_OTH,WS_HNDW_H_OBS,WS_HNDW_H_SPW,WS_HNDW_H_WCL,WS_HNDW_H_WTO,WS_HNDW_H_SPO,WS_HNDW_H_CLO,WS_HNDW_H_NON,HC_FLRM_H_NAT,HC_FLRM_H_ETH,HC_FLRM_H_DNG,HC_FLRM_H_RUD,HC_FLRM_H_WDP,HC_FLRM_H_PLM,HC_FLRM_H_FIN,HC_FLRM_H_PQT,HC_FLRM_H_VIN,HC_FLRM_H_CER,HC_FLRM_H_CEM,HC_FLRM_H_CPT,HC_FLRM_H_OTH,HC_WIXQ_P_LOW,HC_WIXQ_P_2ND,HC_WIXQ_P_MID,HC_WIXQ_P_4TH,HC_WIXQ_P_HGH,HC_WIXQ_P_GNI,FE_CEBA_W_MNC,FP_CUSA_W_MOD,FP_CUSA_W_NCU,ED_EDUC_W_MYR,HC_HEFF_H_RDO,HC_HEFF_H_TLV,HC_HEFF_H_MPH,HC_AGON_H_LND,HC_AGON_H_ANM'

ffp = NULL

for (i in seq_along(countries)) {
  print(i)
  
  temp = loadDHS(breakdown = 'all', indicators = indicators, countries = countries[i], 
                 years = years, apiKey = apiKey, numResults = 5000)
  
  ffp = rbind(temp, ffp)  
}

write.csv(ffp, '~/Documents/USAID/Kyla - FFP reshaping/DHS_data_laura.csv')
